version: 0.2

phases: 
  install: 
    commands:
      - echo Installing Serverless...
      - npm install -g serverless

  pre_build: 
    commands:
      - echo Install source NPM dependencies...
      - npm install
  build: 
    commands:
      - echo Deployment Started on `date`
      - echo Deploying with the Serverless Framework
      - sls login
      - sls deploy -s prod
  post_build: 
    commands:
      - echo Deployment completed on `date`
      